Add controllers
isalamatov/java-shareit pull request #2
Opened 2022-11-21 12:42 UTC by isalamatov

2022-11-22 21:10 UTC, sergeymamonov requested changes

2022-11-22 21:10 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/impl/ItemRepositoryImpl.java
> +                throw new RuntimeException(e);
Не нужно кидать рантайм ошибку. Рантайм ошибка - это общая ошибка, то есть по ней сложно понять, в чем причина ошибки. По IllegalAccessException куда проще понять в чем была причина. То есть в блоке catch нужно написать код, что нужно выполнить сервису, если произошла такая ситуация.

2022-11-23 06:40 UTC, isalamatov commented on src/main/java/ru/practicum/shareit/item/handlers/ItemExceptionHandler.java
> +    }
Добавил

2022-11-23 06:41 UTC, isalamatov commented on src/main/java/ru/practicum/shareit/item/impl/ItemRepositoryImpl.java
> +    private final HashMap<Long, List<Item>> items;
Исправлено

2022-11-23 06:43 UTC, isalamatov commented on src/main/java/ru/practicum/shareit/item/impl/ItemRepositoryImpl.java
> +        this.items = new HashMap<>();
Исправлено.

2022-11-23 07:05 UTC, isalamatov commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private ru.practicum.shareit.item.model.Item item;
Артефакты авторефакторинга. Исправил.

2022-11-23 07:06 UTC, isalamatov commented on src/main/java/ru/practicum/shareit/item/exceptions/ItemAlreadyExistsException.java
> +        log.debug("Item with id {} already exists", itemId);
Убрал логирование из всех исключений.

2022-11-23 07:56 UTC, isalamatov commented on src/main/java/ru/practicum/shareit/item/impl/ItemRepositoryImpl.java
> +                throw new RuntimeException(e);
Исправлено, добавил журналирование.

2022-11-23 21:03 UTC, sergeymamonov approved these changes

2022-11-23 21:03 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/impl/ItemRepositoryImpl.java
> +                log.warn("Mapping partial DTO fields error with message {}", e.getMessage());
На всякий случай уточню. так как ошибка ловится и обрабатывается, а новая ошибка не генерится, то в случае возникновения ошибки в блоке try, выполнится блок catch и программа продолжит работу. Так и задумывалось?

2022-11-24 06:42 UTC, isalamatov commented on src/main/java/ru/practicum/shareit/item/impl/ItemRepositoryImpl.java
> +                log.warn("Mapping partial DTO fields error with message {}", e.getMessage());
Особо не задумывалось честно говоря, т.к. насколько я понимаю вся эта реализация в корзину - в следующем спринте будем добавлять базу данных .

2022-11-24 06:48 UTC, isalamatov commented on src/main/java/ru/practicum/shareit/item/handlers/ItemExceptionHandler.java
> +    }
Попробовал, не проходит тесты. Данный handler всем исключениям ставит статус код 500.

2022-11-24 06:48 UTC, merged