Add bookings
isalamatov/java-shareit pull request #4
Opened 2022-12-07 16:48 UTC by isalamatov

2022-12-08 17:31 UTC, sergeymamonov requested changes
В некоторых классах конвертера вы используете Mapstruct. И это очень хорошо. Но почему не все конвертеры используют эту библиотеку. Почему не используете в ItemMapper?
Убрать рефлексию из проекта. В вебсервисах она не применима. Она медленная и нарушает принципы ООП.

2022-12-08 17:31 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        User user = userRepository.findById(bookingDto.getBookerId())
Классе конвертере не должно быть никаких запросов в БД, никакой валидации, только конвертация из одного класса в другой. Все это должно быть в классе сервиса.

2022-12-08 17:31 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        User user = userRepository.findById(bookingDto.getBookerId())
Классе конвертере не должно быть никаких запросов в БД, никакой валидации, только конвертация из одного класса в другой. Все это должно быть в классе сервиса.

2022-12-08 17:31 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +        if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o)) return false;
Не очень понимаю причем здесь Hibernate. Попробуйте проще.

2022-12-08 17:31 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +            itemDto = enrichItemDto(itemDto, item);
Посмотрите, как в Java передаются объекты в метод. Потому что здесь происходит лишнее присваивание

2022-12-08 17:31 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +            itemDto = enrichItemDto(itemDto, item);
Аналогично, лишнее присваивание

2022-12-08 17:31 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +        Field[] fields = itemPartialUpdateDto.getClass().getDeclaredFields();
Не нужно использовать рефлексию. Во-первых, это медленно. Во-вторых, это нарушает принципы ООП. Изменение объекта нужно делать через сеттеры.

2022-12-08 17:31 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +        for (Item item : items) {
Здесь делается запросы к БД в цикле. Это большая нагрузка на БД. Затратно по времени из-за передачи по сети. Как в данной ситуации можно уйти от цикла:
1. Выгружаем комментарии, группируем их по вещам и конвертируем в dto
2. Выгружаем подтвержденные бронирования отсортированные по дате начала и группируем их по вещам
3. Для каждой вещи находим последнее и следующее бронирование, а также комментарии и формируем результат

2022-12-08 17:31 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +                .stream()
Здесь идут запросы к БД в цикле. Посмотрите выше написал почему так делать не нужно.

2022-12-09 19:00 UTC, isalamatov commented on src/main/java/ru/practicum/shareit/booking/impl/BookingServiceImpl.java
> +    private <T> T getById(Long id, Class<T> clazz) {
Убрал. Особой цели в такой реализации не было, хотел попрактиковаться в написании параметризированных  классов.

2022-12-09 19:00 UTC, isalamatov commented on src/main/java/ru/practicum/shareit/booking/impl/BookingServiceImpl.java
> +        }
Добавил.

2022-12-09 19:01 UTC, isalamatov commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        User user = userRepository.findById(bookingDto.getBookerId())
Исключил. Полностью реализовал маппинг сущностей через возможности библиотеки MapStruct.

2022-12-09 19:01 UTC, isalamatov commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        User user = userRepository.findById(bookingDto.getBookerId())
Исключил, сделал метод проверки в сервисе.

2022-12-09 19:03 UTC, isalamatov commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +            itemDto = enrichItemDto(itemDto, item);
Исключил, т.к. поменялась реализация за счет исключения циклических обращений к БД.

2022-12-09 19:05 UTC, isalamatov commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +            itemDto = enrichItemDto(itemDto, item);
Исключил.

2022-12-09 19:06 UTC, isalamatov commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +        Field[] fields = itemPartialUpdateDto.getClass().getDeclaredFields();
Убрал, сделал через сеттеры.

2022-12-09 19:07 UTC, isalamatov commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +        for (Item item : items) {
Исправил. Теперь выгружается полный список бронирований пользователя из БД, и уже в приложении происходит его обработка в цикле. По заданию, в запросе на получение всех вещей комментарии не обязательны, поэтому задача немного упростилась.

2022-12-09 19:07 UTC, isalamatov commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +                .stream()
Исправил.

2022-12-09 20:54 UTC, sergeymamonov approved these changes

2022-12-11 08:06 UTC, merged