refactor: after all verifications
isalamatov/java-shareit pull request #5
Opened 2022-12-24 18:36 UTC by isalamatov

2022-12-24 21:07 UTC, sergeymamonov requested changes

2022-12-25 07:28 UTC, isalamatov commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        User user = userService.get(userId);
Чтобы проверить, есть ли пользователь в базе, не перегружая метод сервиса дополнительным параметром.  Можно присваивание убрать, или инджектить сразу репозиторий с методом existById.

2022-12-26 11:28 UTC, sergeymamonov approved these changes

2022-12-26 11:28 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        User user = userService.get(userId);
Проверку, есть ли пользователь или нет, нужно делать в сервисе, не не здесь.
Переменная User user потом нигде не используется, то есть ее не нужно было создавать.
Вызываем userService.get(userId), и ожидается, что таким образом мы проверяем наличия юзера в БД, но из названия метода это не очевидно. Метод должен делать одну задачу и эта задача должна быть зашита в названии метода. Поэтому лучше, чтобы проверка была явная в отдельном коде. То есть userService.get(userId) что-то возвращает, а потом мы валидируем то, что вернул userService.get(userId)

2022-12-26 11:28 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        User requestor = userService.get(requestorId);
Всю подобную логику нужно перенести в сервис. Контроллер делает незначительную работу, в основном вызывает нужный метод сервиса. А вся логика работы уже в сервисе.

2022-12-27 08:09 UTC, merged