Add docker
isalamatov/java-shareit pull request #6
Opened 2023-01-12 12:06 UTC by isalamatov

2023-01-13 14:36 UTC, sergeymamonov requested changes
В главном помнике проекта не должно быть <build><plugins>…</plugins></build>. В классах ...Handler основного сервиса может ли быть обработчик для HttpStatus.BAD_REQUEST? В микросервисе server в классах сервиса типа BookingServiceImpl уже не нужна проверка  if (from < 0 || size <= 0). И не нужны методы типа validate(). Странный CommentController. Он нужен в таком виде? Из основного сервиса нужно удалить проверки типа @NotBlank(message = "Item name should not be blank")

2023-01-13 14:36 UTC, sergeymamonov commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        return get("/owner?state={state}&from={from}&size={size}", userId, parameters);
Лучше выносить все литералы из кода в константы или ресурсные файлы.

2023-01-13 14:36 UTC, sergeymamonov commented on gateway/src/main/java/ru/practicum/shareit/item/ItemClient.java
> +        ResponseEntity<Object> result = get("", ownerId);
Можно сразу возвращать результат выражения без создания дополнительной переменной.

2023-01-13 14:36 UTC, sergeymamonov commented on pom.xml
> +<!--        <resources>-->
Закомменированный код оставлять нельзя.

2023-01-14 06:07 UTC, isalamatov commented on pom.xml
> +<!--        <resources>-->
исправлено

2023-01-14 06:07 UTC, isalamatov commented on gateway/src/main/java/ru/practicum/shareit/item/ItemClient.java
> +        ResponseEntity<Object> result = get("", ownerId);
исправлено

2023-01-14 11:40 UTC, isalamatov commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        return get("/owner?state={state}&from={from}&size={size}", userId, parameters);
Вынес все литералы с названиями параметров (кроме названий endpoint)  в файл. От Handler для HttpStatus.BAD_REQUEST полностью избавиться нельзя, т.к. там есть проверки наличия сущностей, по которым в тестах также ожидается в ответе статус код 400. CommentController убрал, он конечно же лишний. Валидацию из классов сервера убрал.

2023-01-14 12:32 UTC, sergeymamonov approved these changes

2023-01-15 06:24 UTC, merged